# Generated by Django 5.1.1 on 2024-09-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
