# Generated by Django 5.1.1 on 2024-09-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='method',
        ),
    ]
